version: '2'
services:
  server_wgui:
     build: .

     container_name: ossec_server

     network_mode: "bridge"

     volumes:
        - "/home/centos/log_concentrator/ossec/data:/var/ossec/data"

     ports:
        - "1514:1514/udp"
        - "1515:1515"
        - "80:80"
